[book]
authors = ["Stanisław Małolepszy"]
language = "pl"
multilingual = false
src = "src"
title = "TEOHIPHIP Skirmish"
description = "Taktyczna gra skirmishowa z elementami RPG, osadzona w absurdalnym świecie podróży w czasie inspirowanym 'Podróżą dwudziestą' Stanisława Lema"

[output.html]
git-repository-url = "https://github.com/stasm/TEOHIPHIP"
no-section-label = true

[output.html.search]
enable = true
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
